// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.eiei.domain;

import com.sut.eiei.domain.Eiei;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Eiei_Roo_Configurable {
    
    declare @type: Eiei: @Configurable;
    
}
