// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.eiei.domain;

import com.sut.eiei.domain.Eiei;

privileged aspect Eiei_Roo_JavaBean {
    
    public String Eiei.getEieiza() {
        return this.eieiza;
    }
    
    public void Eiei.setEieiza(String eieiza) {
        this.eieiza = eieiza;
    }
    
}
